Migrate to typescript
mljs/confusion-matrix pull request #6
Opened 2022-12-02 14:11 UTC by josoriom

2022-12-02 14:51 UTC, stropitek requested changes

2022-12-02 14:51 UTC, stropitek commented on src/index.ts
> +    actual: any[],
since the algorithm uses strict equality, I don't think we should allow anything else than `boolean`, `number` or `string`

2022-12-02 14:51 UTC, stropitek commented on src/index.ts
> +    predicted: any[],
ditto

2022-12-02 14:51 UTC, stropitek commented on src/index.ts
> +  getTruePositiveCount(label: any): number {
ditto

2022-12-02 14:51 UTC, stropitek commented on src/index.ts
> +  getTrueNegativeCount(label: any) {
ditto

2022-12-02 14:51 UTC, stropitek commented on src/index.ts
> +  getFalsePositiveCount(label: any) {
ditto

2022-12-02 14:51 UTC, stropitek commented on src/index.ts
> +  getFalseNegativeCount(label: any): number {
ditto

2022-12-02 14:51 UTC, stropitek commented on src/index.ts
> +  getPositiveCount(label: any) {
ditto

2022-12-02 14:51 UTC, stropitek commented on src/index.ts
> +  getNegativeCount(label: any) {
ditto

2022-12-02 14:51 UTC, stropitek commented on src/index.ts
> +  getIndex(label: any) {
ditto

2022-12-02 14:51 UTC, stropitek commented on src/index.ts
> +  getTruePositiveRate(label: any) {
ditto

2022-12-02 14:52 UTC, stropitek commented
I did not put a comment on every line because almost every line change is affected ^^

2022-12-02 16:00 UTC, targos commented on src/index.ts
>   * @param {Array<any>} labels - Labels of the confusion matrix, a 1D Array
you should also remove all types from the JSDoc comments

2022-12-02 16:01 UTC, targos commented on package.json
> +    "cheminfo-build": "^1.1.11",
Please remove this and the build script.

2022-12-08 15:29 UTC, stropitek commented on src/index.ts
> +  getNegativeCount(label: boolean | number | string) {
Please create a type `Label` that you can reuse everywhere

2022-12-08 15:29 UTC, stropitek commented on src/__tests__/fromLabels.test.ts
> +        return (a as number) - (b as number);
okay this is not ideal but we can fix that in another PR

(we should use a generic so that the correct type can be inferred)

2022-12-11 02:55 UTC, josoriom commented on src/__tests__/fromLabels.test.ts
> +        return (a as number) - (b as number);
Do you have any example about this?

2022-12-12 13:13 UTC, stropitek commented on src/__tests__/fromLabels.test.ts
> +        return (a as number) - (b as number);
I created this issue: #7 so we can merge this PR without this fixed.

We can have a pair-programming session where I show you how to work with those generics

2022-12-12 13:15 UTC, stropitek commented on src/index.ts
> +  getNegativeCount(label: boolean | number | string) {
@josoriom can you address this?

2022-12-12 13:49 UTC, josoriom commented on src/__tests__/fromLabels.test.ts
> +        return (a as number) - (b as number);
Nice, thanks!

2022-12-12 13:49 UTC, josoriom commented on src/index.ts
> +  getNegativeCount(label: boolean | number | string) {
Sure

2022-12-12 15:11 UTC, merged